server:
  port: 9999
  max-http-header-size: 102400
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30
      # tomcat最大线程数，默认为200
      max: 800


spring:
  #邮件发送配置
  mail:
    username: email
    password: password
    host: smtp.qq.com
    # 开启加密授权验证
    properties:
      mail:
        smtp:
          ssl:
            enable:
              true

  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 14
    password: password

  #时间戳统一转换
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8


# 自动签到接口
cookie:
  # cordCloud
  cordCloud:
    name: cordCloud
    checkIn: https://cordcloud.biz/user/checkin
    login: https://www.c-cloud.xyz/auth/login

